package com.isw.view;

import com.isw.controller.TallerController;
import com.isw.model.Alumno;
import com.isw.model.Inscripcion;
import com.isw.model.InscripcionException;
import com.isw.model.Taller;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Ángel Ruíz García - 00000248171
 */
public class PantallaInscripcion extends javax.swing.JFrame {

    private TallerController controller;
    private JList<Taller> listaTaller;

    public PantallaInscripcion() {
        initComponents();
        controller = new TallerController();
        inicializarVista();
    }

    private void inicializarVista() {
        // Crear lista de talleres
        listaTaller = new JList<>(controller.obtenerTalleres().toArray(new Taller[0]));
        listaTaller.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listaTalleres.setViewportView(listaTaller);

        // Usuario selecciona un taller
        listaTaller.addListSelectionListener(e -> {
            Taller t = listaTaller.getSelectedValue();
            if (t != null) {
                txaDetallesTaller.setText(t.detalles()); // Muestra detalles
            }
        });

        // Buscar alumno
        btnBuscarAlumno1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String id = txtID.getText().trim();
                if (id.isEmpty()) {
                    JOptionPane.showMessageDialog(PantallaInscripcion.this, "Por favor ingresa un ID de alumno.");
                    return;
                }

                Alumno alumno = controller.buscarAlumno(id);
                if (alumno != null) {
                    txaInfoAlumno.setText(alumno.mostrarDatos());
                } else {
                    txaInfoAlumno.setText("No se encontró ningún alumno con ese ID.");
                }
            }
        });

        // Inscribir alumno
        btnInscribirAlumno.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String id = txtID.getText().trim();
                Taller taller = listaTaller.getSelectedValue();

                if (taller == null) {
                    JOptionPane.showMessageDialog(PantallaInscripcion.this, "Selecciona un taller");
                    return;
                }

                if (id.isEmpty()) {
                    JOptionPane.showMessageDialog(PantallaInscripcion.this, "Ingresa un ID.");
                    return;
                }

                try {
                    Inscripcion ins = controller.inscribir(id, taller.getId());
                    txaInfoAlumno.setText(ins.generarTicket());
                    txaDetallesTaller.setText(taller.detalles()); // Muestra detalles actualizados
                    JOptionPane.showMessageDialog(PantallaInscripcion.this, "Inscripción realizada con éxito.");
                } catch (InscripcionException ex) {
                    JOptionPane.showMessageDialog(PantallaInscripcion.this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelTalleres = new javax.swing.JPanel();
        lblDisponibles = new javax.swing.JLabel();
        listaTalleres = new javax.swing.JScrollPane();
        panelTallerDetalles = new javax.swing.JPanel();
        lblDetalles = new javax.swing.JLabel();
        txaDetallesTaller = new javax.swing.JTextArea();
        panelAlumnoInfo = new javax.swing.JPanel();
        lblAlumno = new javax.swing.JLabel();
        txaInfoAlumno = new javax.swing.JTextArea();
        btnInscribirAlumno = new javax.swing.JButton();
        panelInscribir = new javax.swing.JPanel();
        btnBuscarAlumno1 = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(45, 49, 66));

        panelTalleres.setBackground(new java.awt.Color(191, 192, 192));

        lblDisponibles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDisponibles.setForeground(new java.awt.Color(255, 102, 0));
        lblDisponibles.setText("Talleres disponibles:");

        listaTalleres.setBackground(new java.awt.Color(191, 192, 192));
        listaTalleres.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelTalleresLayout = new javax.swing.GroupLayout(panelTalleres);
        panelTalleres.setLayout(panelTalleresLayout);
        panelTalleresLayout.setHorizontalGroup(
            panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTalleresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaTalleres)
                    .addGroup(panelTalleresLayout.createSequentialGroup()
                        .addComponent(lblDisponibles)
                        .addGap(0, 170, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelTalleresLayout.setVerticalGroup(
            panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTalleresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaTalleres)
                .addContainerGap())
        );

        panelTallerDetalles.setBackground(new java.awt.Color(191, 192, 192));

        lblDetalles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDetalles.setForeground(new java.awt.Color(255, 102, 0));
        lblDetalles.setText("Detalles del taller:");

        txaDetallesTaller.setEditable(false);
        txaDetallesTaller.setBackground(new java.awt.Color(191, 192, 192));
        txaDetallesTaller.setColumns(20);
        txaDetallesTaller.setForeground(new java.awt.Color(255, 255, 255));
        txaDetallesTaller.setRows(5);

        javax.swing.GroupLayout panelTallerDetallesLayout = new javax.swing.GroupLayout(panelTallerDetalles);
        panelTallerDetalles.setLayout(panelTallerDetallesLayout);
        panelTallerDetallesLayout.setHorizontalGroup(
            panelTallerDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTallerDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTallerDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTallerDetallesLayout.createSequentialGroup()
                        .addComponent(lblDetalles)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txaDetallesTaller, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTallerDetallesLayout.setVerticalGroup(
            panelTallerDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTallerDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDetalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txaDetallesTaller)
                .addContainerGap())
        );

        panelAlumnoInfo.setBackground(new java.awt.Color(191, 192, 192));

        lblAlumno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAlumno.setForeground(new java.awt.Color(255, 102, 0));
        lblAlumno.setText("Alumno");

        txaInfoAlumno.setEditable(false);
        txaInfoAlumno.setBackground(new java.awt.Color(191, 192, 192));
        txaInfoAlumno.setColumns(20);
        txaInfoAlumno.setForeground(new java.awt.Color(255, 255, 255));
        txaInfoAlumno.setRows(5);

        btnInscribirAlumno.setBackground(new java.awt.Color(79, 93, 117));
        btnInscribirAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btnInscribirAlumno.setText("Inscribirse");

        javax.swing.GroupLayout panelAlumnoInfoLayout = new javax.swing.GroupLayout(panelAlumnoInfo);
        panelAlumnoInfo.setLayout(panelAlumnoInfoLayout);
        panelAlumnoInfoLayout.setHorizontalGroup(
            panelAlumnoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlumnoInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlumnoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlumnoInfoLayout.createSequentialGroup()
                        .addComponent(lblAlumno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txaInfoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlumnoInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInscribirAlumno)
                .addGap(111, 111, 111))
        );
        panelAlumnoInfoLayout.setVerticalGroup(
            panelAlumnoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlumnoInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txaInfoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInscribirAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelInscribir.setBackground(new java.awt.Color(191, 192, 192));

        btnBuscarAlumno1.setBackground(new java.awt.Color(79, 93, 117));
        btnBuscarAlumno1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAlumno1.setText("Buscar Alumno");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresa el ID del alumno:");

        javax.swing.GroupLayout panelInscribirLayout = new javax.swing.GroupLayout(panelInscribir);
        panelInscribir.setLayout(panelInscribirLayout);
        panelInscribirLayout.setHorizontalGroup(
            panelInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInscribirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarAlumno1)
                .addGap(316, 316, 316))
        );
        panelInscribirLayout.setVerticalGroup(
            panelInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInscribirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarAlumno1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(panelTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelTallerDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelAlumnoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAlumnoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTallerDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTalleres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAlumno1;
    private javax.swing.JButton btnInscribirAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JLabel lblDisponibles;
    private javax.swing.JScrollPane listaTalleres;
    private javax.swing.JPanel panelAlumnoInfo;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelInscribir;
    private javax.swing.JPanel panelTallerDetalles;
    private javax.swing.JPanel panelTalleres;
    private javax.swing.JTextArea txaDetallesTaller;
    private javax.swing.JTextArea txaInfoAlumno;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
