package com.isw.view;

/**
 *
 * @author Ángel Ruíz García - 00000248171
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelTalleres = new javax.swing.JPanel();
        lblDisponibles = new javax.swing.JLabel();
        listaTalleres = new javax.swing.JScrollPane();
        panelTallerDetalles = new javax.swing.JPanel();
        lblDetalles = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        lblDisponibles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDisponibles.setForeground(new java.awt.Color(255, 102, 0));
        lblDisponibles.setText("Talleres disponibles:");

        javax.swing.GroupLayout panelTalleresLayout = new javax.swing.GroupLayout(panelTalleres);
        panelTalleres.setLayout(panelTalleresLayout);
        panelTalleresLayout.setHorizontalGroup(
            panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTalleresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaTalleres)
                    .addGroup(panelTalleresLayout.createSequentialGroup()
                        .addComponent(lblDisponibles)
                        .addGap(0, 170, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelTalleresLayout.setVerticalGroup(
            panelTalleresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTalleresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaTalleres)
                .addContainerGap())
        );

        lblDetalles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDetalles.setForeground(new java.awt.Color(255, 102, 0));
        lblDetalles.setText("Detalles del taller:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);

        javax.swing.GroupLayout panelTallerDetallesLayout = new javax.swing.GroupLayout(panelTallerDetalles);
        panelTallerDetalles.setLayout(panelTallerDetallesLayout);
        panelTallerDetallesLayout.setHorizontalGroup(
            panelTallerDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTallerDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTallerDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTallerDetallesLayout.createSequentialGroup()
                        .addComponent(lblDetalles)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTallerDetallesLayout.setVerticalGroup(
            panelTallerDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTallerDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDetalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelTallerDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTallerDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTalleres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JLabel lblDisponibles;
    private javax.swing.JScrollPane listaTalleres;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelTallerDetalles;
    private javax.swing.JPanel panelTalleres;
    // End of variables declaration//GEN-END:variables
}
